### PR TITLE
Update Naiveproxy Plugin

### PR DESCRIPTION
**Pull request by amd64v3**
Update Naiveproxy plugin to v108.0.5359.94-1

### CODE REVIEW

**Comment by reeceyng** [comment]
请问你知道怎么在自己的仓库里build naive plugin吗？还是只能pr到这里来build？

**Comment by amd64v3** [comment]
You can run "release_naive.yml" manually in your fork, but it will release unsigned apks, you can sign it by yourself.

**Comment by amd64v3** [comment]
> 请问你知道怎么在自己的仓库里build naive plugin吗？还是只能pr到这里来build？

You can run "release_naive.yml" manually in your fork, but it will release unsigned apks, you can sign it by yourself.

**Comment by reeceyng** [comment]
> > 请问你知道怎么在自己的仓库里build naive plugin吗？还是只能pr到这里来build？
> 
> You can run "release_naive.yml" manually in your fork, but it will release unsigned apks, you can sign it by yourself.

Do you know how to fix this error?
https://github.com/reeceyng/SagerNet/actions/runs/3613213057/jobs/6089203077

**Comment by Bryan2333** [comment]
> > > 请问你知道怎么在自己的仓库里build naive plugin吗？还是只能pr到这里来build？
> > 
> > 
> > You can run "release_naive.yml" manually in your fork, but it will release unsigned apks, you can sign it by yourself.
> 
> Do you know how to fix this error? https://github.com/reeceyng/SagerNet/actions/runs/3613213057/jobs/6089203077

I met the same problem.

**Comment by amd64v3** [comment]
> > > 请问你知道怎么在自己的仓库里build naive plugin吗？还是只能pr到这里来build？
> > 
> > 
> > You can run "release_naive.yml" manually in your fork, but it will release unsigned apks, you can sign it by yourself.
> 
> Do you know how to fix this error? https://github.com/reeceyng/SagerNet/actions/runs/3613213057/jobs/6089203077

Ha-ha, if you check the code carefully, you will find the answer.

**Comment by amd64v3** [comment]
> > > 请问你知道怎么在自己的仓库里build naive plugin吗？还是只能pr到这里来build？
> > 
> > 
> > You can run "release_naive.yml" manually in your fork, but it will release unsigned apks, you can sign it by yourself.
> 
> Do you know how to fix this error? https://github.com/reeceyng/SagerNet/actions/runs/3613213057/jobs/6089203077

This is the <a href ="https://github.com/SagerNet/SagerNet/issues/495#issuecomment-1169433009">reason</a> why SagerNet's release  action automatically cancelled.

**Comment by Bryan2333** [comment]
> > > > 请问你知道怎么在自己的仓库里build naive plugin吗？还是只能pr到这里来build？
> > > 
> > > 
> > > You can run "release_naive.yml" manually in your fork, but it will release unsigned apks, you can sign it by yourself.
> > 
> > 
> > Do you know how to fix this error? https://github.com/reeceyng/SagerNet/actions/runs/3613213057/jobs/6089203077
> 
> This is the [reason](https://github.com/SagerNet/SagerNet/issues/495#issuecomment-1169433009) why SagerNet's release action automatically cancelled.

How can I use my custom signature? I replace the `release.keystore` file, but it did not work.

**Comment by reeceyng** [comment]
> > > > > > 请问你知道怎么在自己的库里build naive plugin吗？还是只能pr到这里来build？
> > > > > 
> > > > > 
> > > > > 您可以在您的 fork 中手动运行“release_naive.yml”，但它会发布未签名的 apk，您可以自己签名。
> > > > 
> > > > 
> > > > 你知道如何解决这个错误吗？https://github.com/reeceyng/SagerNet/actions/runs/3613213057/jobs/6089203077
> > > 
> > > 
> > > 这就是 SagerNet 的发布动作自动取消的[原因。](https://github.com/SagerNet/SagerNet/issues/495#issuecomment-1169433009)
> > 
> > 
> > 如何使用我的自定义签名？我替换了`release.keystore`文件，但没有用。
> 
> 你可以使用我最新的 naive-plugin building assets : https://github.com/bolucat/SagerNet/releases，顺便说一句，由于签名冲突，你必须卸载你以前的 naive-plugin

What should secrets.LOCAL_PROPERTIES be set to?

**Comment by Bryan2333** [comment]
> > > > > > > > 请问你知道怎么在自己的库里build naive plugin吗？还是只能pr到这里来build？
> > > > > > > 
> > > > > > > 
> > > > > > > 您可以在您的 fork 中手动运行“release_naive.yml”，但它会发布未签名的 apk，您可以自己签名。
> > > > > > 
> > > > > > 
> > > > > > 你知道如何解决这个错误吗？https://github.com/reeceyng/SagerNet/actions/runs/3613213057/jobs/6089203077
> > > > > 
> > > > > 
> > > > > 这就是 SagerNet 的发布动作自动取消的[原因。](https://github.com/SagerNet/SagerNet/issues/495#issuecomment-1169433009)
> > > > 
> > > > 
> > > > 如何使用我的自定义签名？我替换了`release.keystore`文件，但没有用。
> > > 
> > > 
> > > 你可以使用我最新的 naive-plugin building assets : [https://github.com/bolucat/SagerNet/releases，顺便说一句，由于签名冲突，你必须卸载你以前的](https://github.com/bolucat/SagerNet/releases%EF%BC%8C%E9%A1%BA%E4%BE%BF%E8%AF%B4%E4%B8%80%E5%8F%A5%EF%BC%8C%E7%94%B1%E4%BA%8E%E7%AD%BE%E5%90%8D%E5%86%B2%E7%AA%81%EF%BC%8C%E4%BD%A0%E5%BF%85%E9%A1%BB%E5%8D%B8%E8%BD%BD%E4%BD%A0%E4%BB%A5%E5%89%8D%E7%9A%84) naive-plugin
> > 
> > 
> > What should secrets.LOCAL_PROPERTIES be set to?
> 
> 1. Generate a key and replace the `release.keystore` in the root folder
> 2. Write your secrets like this format below:
> 
> ```shell
> KEYSTORE_PASS=Your_Password
> ALIAS_NAME=Your_Alias_Name
> ALIAS_PASS=Your_Password
> ```
> 
> Replace `Your_Password` to your password, `Your_Alias_Name` to your alias name, these values should be set in step 1 when you generate your key 3. Copy the secrets in step 2 and go to this website : https://www.base64encode.org , paste your secrets and click `ENCODE`, you will get a super long string like this : `S0VZU1RPUkVfUEFTUz1Zb3VyX1Bhc3N3b3JkCkFMSUFTX05BTUU9WW91cl9BbGlhc19OYW1lCkFMSUFTX1BBU1M9WW91cl9QYXNzd29yZA==` 4. Add the secrets to your GitHub repository, tutorial is here : https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository . The `Name` value is `LOCAL_PROPERTIES` , and the `Secret` value is the string you got from step 3, like `S0VZU1RPUkVfUEFTUz1Zb3VyX1Bhc3N3b3JkCkFMSUFTX05BTUU9WW91cl9BbGlhc19OYW1lCkFMSUFTX1BBU1M9WW91cl9QYXNzd29yZA==` 5. After doing all of this, trigger the GitHub action and it should work fine

Build successfully, thanks for your help.

**Pull request merged**
